export const PLAN_PRICE_IDS = {
	MONTHLY_PRO: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRO_PRICE_ID!,
	YEARLY_PRO: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRO_PRICE_ID!,
	MONTHLY_PREMIUM: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PREMIUM_PRICE_ID!,
	YEARLY_PREMIUM: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PREMIUM_PRICE_ID!
}